url: https://mkeppeler.github.io
title: IBM Innovation Day - Labs
description: This site offers hands-on labs for IBM Concert Workflows.
theme: jekyll-theme-architect

kramdown:
  syntax_highlighter_opts:
    disable : true
