theme: jekyll-theme-minimal
title: IBM Innovation Day - Labs
description: This site offers hands-on labs for IBM Concert Workflows.

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
